config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :sessions, only: [:create]

  resources :users, only: %i[create update] do
    scope module: :users do
      resources :messaged_users, only: [:index]
      resource :mentar, only: %i[show update]
    end

    collection do
      get :current_user, to: "users#show"
      scope module: :users do
        get :consultations, to: "consultations#index"
        resources :with_id, only: [:show]
      end
    end
  end

  resources :mentars, only: %i[index show] do
    collection do
      get :index, to: "mentars#index"
      get :detail, to: "mentars#detail"
      post :update_c, to: "mentars#update_c"
      scope module: :mentars do
        get :sort, to: "sorts#index"
        get :search, to: "search#index"
      end
    end
  end

  resource :direct_message_comment, only: %i[show create]

  resources :notifications, only: %i[index create destroy] do
    collection do
      scope module: :notifications do
        delete :all, to: "all#destroy"
      end
    end
  end

  resources :consultations, only: %i[index create show] do
    scope module: :consultations do
      resource :status, only: [:update]
    end
    collection do
      get :user_consultations, to: "consultations#user_consultations"
      scope module: :consultations do
        get :sort, to: "sorts#index"
        get :search, to: "search#index"
      end
    end
  end

  resources :comments, only: %i[index create]

  namespace :admin do
    get '/', to: "home#index"
    resources :users do
      resource :user_logs, only: [:show]

      scope module: :users do
        resource :freeze, only: [:create, :destroy]
      end
    end

  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_token

  has_many :direct_message_notifications
  has_one_attached :image
  has_one :mentar
  has_many :comments, class_name: "Comment", foreign_key: "sender_id"
  has_many :user_logs

  validates :email, presence: true
  validates :name, presence: true

  enum status: { active: 0, stop: 1 }

  def create_login_log
    UserLog.create(user_id: self.id, action_type: "login")
  end

  def last_login_date
    user_logs&.order(created_at: :desc)&.first&.strftime("%Y%m%d")  
  end

  def freeze_account
    stop!
  end

  def restart_account
    active!
  end
end

app/controllers/admin/users/freezes_controller.rb
class Admin::Users::FreezesController < ApplicationController
    before_action :set_user

    def create
        @user.freeze_account
    end

    def destroy
        @user.restart_account
    end

    private

    def set_user
        @user = User.find(params[:user_id])
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :set_user, only: [:show]

    def index
        @users = User.includes([:mentar]).all
    end

    def show
    end
    
    private
    
    def set_user
        @user = User.find(params[:id])
    end
end

app/controllers/users/consultations_controller.rb
# frozen_string_literal: true

class Users::ConsultationsController < ApplicationController
  def index
    user = User.find_by(token: params[:token])
    consultations = Consultation.includes(:user).where(user_id: user.id).order(status: :asc).order(created_at: :desc)
    json_string = ConsultationSerializer.new(consultations).serialized_json
    render json: json_string
  end
end

app/controllers/users/mentars_controller.rb
# frozen_string_literal: true

class Users::MentarsController < ApplicationController
  def show
    user = User.find_by(token: params[:user_id])
    mentar = Mentar.includes(comments: :sender).find_by(user_id: user.id)
    options = {}
    options[:include] = [:comments]
    json_string = MentarSerializer.new(mentar, options).serialized_json
    render json: json_string
  end

  def update
    user = User.find_by(token: params[:token])
    mentar = Mentar.find_or_initialize_by(user_id: user.id)
    mentar.update(description: params[:description], category: params[:category], sex: params[:sex])
    mentar.save
  end
end

app/controllers/users/messaged_users_controller.rb
# frozen_string_literal: true

class Users::MessagedUsersController < ApplicationController
  def index
    user = User.find_by(token: params[:user_id])
    senders_ids = Comment.where(reciever_id: user.id, target_type: nil).map(&:sender_id).to_a.uniq
    recievers_ids = Comment.where(sender_id: user.id, target_type: nil).map(&:reciever_id).to_a.uniq
    user_ids = (senders_ids + recievers_ids).uniq
    messaged_users = User.includes(:mentar, { image_attachment: :blob }).find(user_ids)

    json_string = UserSerializer.new(messaged_users, params: { currentUserId: user.id, showNotification: true }).serialized_json
    render json: json_string
  end
end

app/controllers/users/with_id_controller.rb
# frozen_string_literal: true

class Users::WithIdController < ApplicationController
  def show
    user = User.find(params[:id])

    json_string = UserSerializer.new(user).serialized_json
    render json: json_string
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  require "pusher"

  def create
    User.create(email: params[:email], password: params[:password], name: params[:name], image: params[:image])
  end

  def show
    user = User.find_by(token: params[:token])

    json_string = UserSerializer.new(user).serialized_json
    render json: json_string
  end

  def update
    user = User.find_by(token: params[:id])
    user.update!(user_params)
    render status: 200, json: { status: 200, message: "Success" }
  end

  private

    def user_params
      params.require(:user).permit(:name, :description, :image)
    end
end

app/helpers/admin/users/freezes_helper.rb
module Admin::Users::FreezesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/consultations_helper.rb
# frozen_string_literal: true

module Users::ConsultationsHelper
end

app/helpers/users/mentars_helper.rb
# frozen_string_literal: true

module Users::MentarsHelper
end

app/helpers/users/messaged_users_helper.rb
# frozen_string_literal: true

module Users::MessagedUsersHelper
end

app/helpers/users/with_id_helper.rb
# frozen_string_literal: true

module Users::WithIdHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/users/index.html.erb
<% breadcrumb :admin_users %>

<div class="container-fluid">
    <table class="table table-hover mt-5">
        <thead>
            <tr>
                <th scope="col">名前</th>
                <th scope="col">メールアドレス</th>
                <th>最後のログイン</th>
                <th>メンター登録</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.last_login_date || "ログイン履歴無し" %></td>
                <td><%= user.mentar ? "●" : "×" %></td>
                <td>
                    <%= link_to admin_user_path(user), class: "btn btn-sm btn-secondary" do %>
                    詳細
                    <% end %>
                </td>
                <td>
                    <% if user.active? %>
                    <%= render "/admin/users/freezes/freeze_button.html.erb", user: user %>
                    <% elsif user.stop? %>
                    <%= render "/admin/users/freezes/restart_button.html.erb", user: user %>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admin/users/show.html.erb
<% breadcrumb :admin_users_show %>

<div class="container">
    <div class="card p-5">
        <div class="d-flex justify-content-center aligh-items-center mb-3">
            <%= image_tag @user.image %>
        </div>
        <div class="border-bottom row mb-5">
            <p class="col-md-3">ユーザー名: </p>
            <p class="col-md-9"><%= @user.name %></p>
        </div>
        <div class="border-bottom row mb-5">
            <p class="col-md-3">メールアドレス: </p>
            <p class="col-md-9"><%= @user.email %></p>
        </div>
        <div class="border-bottom row mb-5">
            <p class="col-md-3">自己紹介文: </p>
            <p class="col-md-9"><%= @user.description %></p>
        </div>
        <div class="border-bottom row mb-5">
            <p class="col-md-3">最終ログイン日時</p>
            <p class="col-md-9"><%= @user.last_login_date || "ログイン履歴無し" %></p>
        </div>
        <div class="m-3 d-flex justify-content-around">
            <%= link_to admin_user_user_logs_path(@user), class: "card p-3 d-flex flex-column justify-content-center align-items-center" do %>
            <p>ログイン履歴詳細</p>
            <i class="fas fa-door-open fa-4x"></i>
            <% end %>
            <div class="card p-3 d-flex flex-column justify-content-center align-items-center">
                <p>投稿記事一覧</p>
                <i class="fas fa-mail-bulk fa-4x"></i>
            </div>
            <div class="card p-3 d-flex flex-column justify-content-center align-items-center">
                <p>投稿コメント一覧</p>
                <i class="fas fa-comments fa-4x"></i>
            </div>
        </div>
    </div>
</div>